version: '3.7'
services:
  easypermit-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: easypermit-frontend
    container_name: easypermit-frontend
    ports:
      - '5000:5000'
    expose:
      - 5000
    env_file:
      - ./.env
