version: '3.7'
services:
  react-hot-reload:
    build:
      context: .
      dockerfile: Dockerfile
    # image: react-hot-reload:easypermit-hot-reload
    # container_name: easypermit-hot-reload
    # volumes:
    #   - .:/home/app
      # - react_hot_reload: /home/app/node_modules
    ports:
      - '3000:3000'
    expose:
      - 3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: yarn start
    networks:
      - default
